# Generated by Django 5.2.4 on 2025-07-26 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            -- Transfer table ownership to postgres (admin)
            ALTER TABLE tenants_branch OWNER TO postgres;
            ALTER TABLE tenants_sales OWNER TO postgres;
            
            -- Enable RLS for Branch table
            ALTER TABLE tenants_branch ENABLE ROW LEVEL SECURITY;
            ALTER TABLE tenants_branch FORCE ROW LEVEL SECURITY;
            
            -- Simple branch access policy
            CREATE POLICY branch_access_policy ON tenants_branch
                FOR ALL
                TO app_role
                USING (id = get_current_branch_id());
            
            -- Enable RLS for Sales table  
            ALTER TABLE tenants_sales ENABLE ROW LEVEL SECURITY;
            ALTER TABLE tenants_sales FORCE ROW LEVEL SECURITY;
            
            -- Simple sales isolation policy
            CREATE POLICY sales_branch_isolation ON tenants_sales
                FOR ALL
                TO app_role
                USING (branch_id = get_current_branch_id());
            
            -- Grant permissions to app_role (not ownership)
            REVOKE ALL ON tenants_branch FROM PUBLIC;
            REVOKE ALL ON tenants_sales FROM PUBLIC;
            
            GRANT SELECT, INSERT, UPDATE, DELETE ON tenants_branch TO app_role;
            GRANT SELECT, INSERT, UPDATE, DELETE ON tenants_sales TO app_role;
            GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO app_role;
            """,
            reverse_sql="""
            -- Remove RLS policies
            DROP POLICY IF EXISTS branch_access_policy ON tenants_branch;
            DROP POLICY IF EXISTS sales_branch_isolation ON tenants_sales;
            
            -- Disable RLS
            ALTER TABLE tenants_branch DISABLE ROW LEVEL SECURITY;
            ALTER TABLE tenants_sales DISABLE ROW LEVEL SECURITY;
            
            -- Restore ownership and permissions
            ALTER TABLE tenants_branch OWNER TO app_user;
            ALTER TABLE tenants_sales OWNER TO app_user;
            GRANT ALL ON tenants_branch TO PUBLIC;
            GRANT ALL ON tenants_sales TO PUBLIC;
            """
        )
    ]
